FROM python:3-bullseye

RUN apt install git
RUN echo "cd / && git clone https://\$USER:\$TOKEN@github.com/tryon-dev/Bow app && cd app && pip install pip --upgrade && pip install -r requirements.txt && python main.py" > run.sh
EXPOSE 5000:5000
WORKDIR /
CMD ["bash", "run.sh"]
